### ISSUE TITLE
Kartikeyamani

### ISSUE THREAD

**Issue by connman4027** [NAU-OSS/jabref#70] opened 2024-09-02 19:58 UTC
The Readme file is currently lengthy and complex, making it challenging for newcomers to comprehend how to contribute effectively to the project.

To enhance accessibility and clarity, I propose relocating the Contributing section to the beginning of the Readme file and streamlining its content where feasible.

I kindly request assistance from anyone willing to dedicate time to address this issue and improve the project's accessibility for all contributors. Thank you!

**Comment by kartikeyamani** [comment] 2024-09-12 03:49
70

**Comment by kartikeyamani** [comment] 2024-09-12 03:58
Hello Myself Karthikeya Gangisetty. I'm so much intrested in Machine learning and computer vision techniques. I want to build projects using these tools. I want to learn open source because it is an easy and rapid way to grow our projects according to market needs. I selected this issue because ReadMe file is like base to any projects that we see and if it's lengthy it is difficult for contributors to understand so we make it as easy as possible.

**Comment by kartikeyamani** [comment] 2024-09-12 04:01
Hey @connman4027  to deal with this issue I need your help because you and I are the only participants who assigned this issue and I would like to gain some insightful knowledge about this project. I sincerely appreciate any help that I can get from you in solving the issue. Thanks in advance.

**Comment by kartikeyamani** [comment] 2024-09-12 04:04
Hey @caiton1  to deal with this issue I need your help because you and I are the only participants who assigned this issue and I would like to gain some insightful knowledge about this project. I sincerely appreciate any help that I can get from you in solving the issue. Thanks in advance.

**Comment by kartikeyamani** [comment] 2024-09-12 04:30
The issue is closed, Thanks everyone for their contributions

**Closed by kartikeyamani** 2024-09-12 04:30 UTC
Labels: non-code contribution
